apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-special-secret"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
type: Opaque
data:
  API_KEY: "{{ .Values.secrets.apiKey | b64enc }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-file-secret"
  namespace: "{{ .Release.Namespace }}"
type: Opaque
data:
  something.json: "{{ .Values.secrets.file | b64enc }}"
