apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-api"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ .Release.Name }}-api"
spec:
  selector:
    app: "{{ .Release.Name }}-api"
  ports:
  - port: 80
    protocol: TCP
    targetPort: {{ .Values.containers.nginx.port }}
